...\" $Header: /usr/src/docbook-to-man/cmd/RCS/docbook-to-man.sh,v 1.3 1996/06/17 03:36:49 fld Exp $
...\"
...\"	transcript compatibility for postscript use.
...\"
...\"	synopsis:  .P! <file.ps>
...\"
.de P!
\\&.
.fl			\" force out current output buffer
\\!%PB
\\!/showpage{}def
...\" the following is from Ken Flowers -- it prevents dictionary overflows
\\!/tempdict 200 dict def tempdict begin
.fl			\" prolog
.sy cat \\$1\" bring in postscript file
...\" the following line matches the tempdict above
\\!end % tempdict %
\\!PE
\\!.
.sp \\$2u	\" move below the image
..
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "sw" "5"
 
.hy 0 
.if n .na
.SH "NAME"
sw \(em POSIX Software Packaging
.SH "SYNOPSIS"
.PP
.nf
Software Packaging Layout
Software Definitions
Software Selections
Extended Definitions
Distributor Keywords
Package Security
Software Definition Files: INFO, INDEX, PSF
Example Package
.fi
.SH "SOFTWARE PACKAGING LAYOUT"
.PP
A package may exist in two forms: as a directory in a file system, or a serial access tar or cpio archive file\&.
A package consists of two main sections: 1) the \fIexported catalog structure\fP, 
and, 2) the \fIsoftware file storage structure\fP\&.
Each section may contain path name components which serve to segregate distribution, product and fileset objects\&.
.PP
Shown below is an example with one (1) product and one (1) fileset\&.
.PP
.nf
\f(CW
.br
 <\fIpath\fP>/ 
 <\fIpath\fP>/\fBcatalog\fP/
 <\fIpath\fP>/\fBcatalog\fP/\fBINDEX\fP 
 <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>
 <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\&.\&.\&.
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIpfiles\fP>/\fBINFO\fP  
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIpfiles\fP>/\&.\&.\&.
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/\fBINFO\fP 
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/\&.\&.\&.
 <\fIpath\fP>/\fBcatalog\fP/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/<\fIscript\fP>
 <\fIpath\fP>/<\fIprod_dir\fP>/
 <\fIpath\fP>/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/
 <\fIpath\fP>/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/<\fIdistribution_files\fP>
 <\fIpath\fP>/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/<\fIdistribution_files\fP>/\&.\&.\&.\fR
.fi
.PP
.PP
The exported catalog structure consists of the files with pathnames
that begin <\fIpath\fP>/\fBcatalog\fP\&.
Note that \fBcatalog\fP is not a legal \fIprod_dir\fP name\&. Also, "\fBdfiles\fP", and
"\fBpfiles\fP" should not be used as control directory names, they are the default names for
the Distribution and Product files directories\&.  The dfiles and pfiles defaults are commonly accepted\&.
.PP
The order of files in a serial access archive is specified and shown above\&.
The order of products and filesets within a product is not specified, although
they must be grouped together\&.
Notably, the \fBINDEX\fP file is the first regular file in the package, followed
by the <\fIdfiles\fP> directory\&.  For each product, the <\fIprod_dir\fP>
is followed immediately by the 
<\fIprod_dir\fP>/<\fIpfiles\fP> directory\&.
.SS "Minimal Package Layout"
.PP
To support extant usage of tar archives, this implementation supports a minimal package layout\&.
The layout is non-intrusive to the current practice of extracting a \&'binary\&' package in the \&'/\&' directory where 
<\fIpath\fP>/ is nil and,
likewise to \&'source\&' packages where
<\fIpath\fP> is typically the package name and version\&.  The use of nil control directories
is not attested to in the POSIX standard\&.
.PP
.nf
\f(CW
.br
 <\fIpath\fP>/ 
 <\fIpath\fP>/\fBcatalog\fP/
 <\fIpath\fP>/\fBcatalog\fP/\fBINDEX\fP 
 <\fIpath\fP>/\fBcatalog\fP/\fBdfiles\fP/
 <\fIpath\fP>/\fBcatalog\fP/\fBdfiles\fP/\fBINFO\fP  
 <\fIpath\fP>/\fBcatalog\fP/\fBdfiles\fP/\&.\&.\&.
 <\fIpath\fP>/\fBcatalog\fP/\fBpfiles\fP/\fBINFO\fP  
 <\fIpath\fP>/\fBcatalog\fP/\fBpfiles\fP/\&.\&.\&.
 <\fIpath\fP>/\fBcatalog\fP/\fBINFO\fP 
 <\fIpath\fP>/<\fIdistribution_files\fP>/\&.\&.\&.\fR
.fi
.PP
.PP
In this layout a single product and fileset have \fIcontrol_directory\fP attributes specified as an empty string\&.
.SS "Distribution Files"
.PP
.nf
catalog/<\fIdfiles\fP>/\&.\&.\&.
.fi
.PP
<\fIdfiles\fP> 
is the value of the \fIdfiles\fP attribute and the default value is "dfiles"\&.
This directory can store an INDEX file or INFO file pertaining to the distribution\&. 
It can also store an attribute of
the distribution as a separate file where file name is the name of the attribute and the file contents the value\&.
.SS "Product Files"
.PP
.nf
catalog/<\fIprod_dir\fP>/<\fIpfiles\fP>/\&.\&.\&.
.fi
.PP
<\fIpfiles\fP> 
is the value of the \fIpfiles\fP attribute and the default value is "pfiles"\&.
This directory can store an INFO file pertaining to the product control_files,  control scripts defined in the INFO file, and all
other distributor-defined control_files\&.
It can also store an attribute of
the product as a separate file\&.
.SS "Fileset Files"
.PP
.nf
catalog/<\fIprod_dir\fP>/<\fIfileset_dir\fP>/\&.\&.\&.
.fi
.PP
This directory contains information in the same form as does the 
\fBProduct Files\fP although pertaining to the fileset\&.
.SS "Control Directory Names"
.PP
The 
<\fIprod_dir\fP>/<\fIfileset_dir\fP>
names are the values of the \fIcontrol_directory\fP attribute for the product and fileset respectively\&.  The
default value is the value of the \fItag\fP attribute\&.
<\fIprod_dir\fP> must be unique within a distribution and
<\fIfileset_dir\fP> must be unique within a product\&.
.SS "File Storage "
.PP
.nf
<\fIprod_dir\fP>/<\fIfileset_dir\fP>/<\fIdistribution_files\fP>/\&.\&.\&.
.fi
.PP
The listing of control directories in the exported catalog structure is repeated and files of the 
distribution appear under these directories in a location determined by the metadata\&.
.PP
The standard does not require that files that are not regular files appear in the storage section\&.
.SH "SOFTWARE DEFINITIONS"
.PP
The Software Definitions are metadata representations of the objects and attributes
recognized by the standard\&.
The right hand column in each definition shows the default attribute value\&.  The defining standard for each attribute is indicated as a
comment (leading \&'#\&' sign) if it is not IEEE-1387\&.2,  other defining standards are XDSA C701 (\fBC701\fP), and, this
implementation (\fBimpl\&.\fP)\&.
.SS "Host Definition"
.PP
.nf
\f(CW host
.br
   hostname     \fIhostname\fP       None
   os_name      \fIos_name\fP        None
   os_release   \fIos_release\fP     None
   os_version   \fIos_version\fP     None
   machine_type \fImachine_type\fP   None\fR
.fi
.PP
.PP
The host definition was attested to only in the informative annex of the standard\&.  An implementation
may chose to define this class\&.
.PP
A host object can contain a \fIdistribution\fP,
or \fIinstalled_software\fP object\&.
 
.SS "Distribution Definition"
.PP
.nf
\f(CW distribution
   layout_version \fIlayout_version\fP  \fB1\&.0\fP 
   path           \fIpath\fP            Implementation Defined
   dfiles         \fIdfiles\fP          \fBdfiles\fP 
   pfiles         \fIpfiles\fP          \fBpfiles\fP 
   uuid           \fIuuid\fP            Empty string\fR
.fi
.PP
.PP
The \fIpath\fP attribute is not in a PSF nor INDEX files\&.
A PSF does not contain a \fIuuid\fP attribute\&.
An INDEX file will contain a \fIlayout_version\fP attribute as
the first attribute\&.
.PP
A distribution object can contain \fIbundles\fP, \fIproducts\fP,
and, \fImedia\fP in the form of software definitions\&.
.PP
The following attributes are recognized as valuable by the Informative Annex of POSIX\&.7\&.2\&.
.PP
.nf
\f(CW   tag                \fItag\fP                Empty string
   title              \fItitle\fP              Empty string
   description        \fIdescription\fP        Empty string
   revision           \fIrevision\fP           Empty string
   media_type         \fImedia_type\fP         Empty string
   copyright          \fIcopyright\fP          Empty string
   create_time        \fIcreate_time\fP        Empty string
   number             \fInumber\fP             Empty string
   architecture       \fIarchitecture\fP       Empty string\fR
.fi
.PP
.PP
The following attributes are recognized by this implementation\&.
.PP
.nf
\f(CW   signature          \fB<\fP \fIpathname\fP  None   # impl\&.
   sig_header   \fB<\fP \fIpathname\fP  None   # impl\&.
   sha1sum            \fB<\fP \fIpathname\fP  None   # impl\&.
   sha512sum           \fB<\fP \fIpathname\fP  None   # impl\&.
   md5sum             \fB<\fP \fIpathname\fP  None   # impl\&.
   adjunct_md5sum     \fB<\fP \fIpathname\fP  None   # impl\&.
   files              \fB<\fP \fIpathname\fP    None  # impl\&.
   control_directory  \fIcontrol_directory\fP      Empty string   # impl\&.
   owner              \fIname\fP                           root   # impl\&.
   group              \fIname\fP                           root   # impl\&.
   mode               \fImode\fP                           \fB0755\fP    # impl\&.
   signer_pgm         \fIutility_name\fP                   GPG    # impl\&.
   signer_pgm_version \fIversion\fP                        \fB1\fP    # impl\&.
   tar_format_emulation_options \fIprogram_options\fP          # impl\&.
   tar_format_emulation_utility \fIsoftware spec\fP            # impl\&.
\fR
.fi
.PP
.PP
The \fIurl\fP attribute is the universal record locator of
the \fIpackager\fP qualified vendor\&.
The \fIcontrol_directory\fP attribute in the 
distribution object appears as the <\fIpath\fP>
leading directory path in the a serial archive package\&.
The \fIowner\fP, \fIgroup\fP, and
\fImode\fP attributes control the file attributes of the single path name prefix\&.
The \fIsignature\fP,
\fIsig_header\fP,
\fImd5sum\fP,
and \fIadjunct_md5sum\fP attributes are described below and are stored as separate files in the dfiles
directory\&. The \fItar_format_emulation_*\fP options define
the GNU tar version and format options that the archive file mimics, these
attributes are used by the \&'checkdigest\&' script\&.
.SS "Installed_software Definition"
.PP
.nf
\f(CW installed_software
   layout_version \fIlayout_version\fP  \fB1\&.0\fP 
   path           \fIpath\fP            Implementation Defined
   dfiles         \fIdfiles\fP          \fBdfiles\fP 
   pfiles         \fIpfiles\fP          \fBdfiles\fP 
   catalog        \fIcatalog\fP         Undefined
   install_time   \fIinstall_time\fP    Undefined       # impl\&.\fR
.fi
.PP
.PP
A software object can be listed (written to stdout) in the form of an INDEX
file by the swlist utility\&.
 
.SS "Media Definition"
.PP
.nf
\f(CW media
   sequence_number \fIsequence_number\fP  \fB1\fP\fR
.fi
.PP
.PP
An INDEX file must contain the \fIsequence_number\fP attribute if
the distribution spans multiple media\&.
 
.SS "Vendor Definition"
.PP
.nf
\f(CW vendor
   the_term_vendor_is_misleading  true                  True or False  #impl
   tag         \fItag\fP           Empty string
   title       \fItitle\fP         Empty string
   description \fIdescription\fP   Empty string
   qualifier   \fIqualifier\fP     Empty string  # impl\&.
   url         \fIurl\fP           Empty string  # impl\&.
   vendor_tag  \fItag\fP           Empty string  # impl\&.\fR
.fi
.PP
.PP
The \fItag\fP attribute is required\&.
The \fIthe_term_vendor_is_misleading\fP is required in a PSF
file to avert a (harmless) warning, please use it\&.  It exists to allow persons, for example,
who are distributors (of existing free software) to qualify themselves away from the connotations
of a "vendor" which has specific meaning not applicable to a free software distributor\&.
A INDEX and PSF files can contain \fBvendor\fP definitions\&.
The \fIvendor_tag\fP attribute contains the vendor\&.\fItag\fP of the upstream distributor\&.
The \fBqualifier\fP attribute value may be one of:
\fBseller\fP, 
\fBauthor\fP, 
\fBpackager\fP, 
\fBmaintainer\fP\&.
A distribution may have more than one vendor definition\&.  They may form a chain of references from
the product\&.\fIvendor_tag\fP to the last vendor referred to by the
vendor\&.\fIvendor_tag\fP attributes\&.
 
.SS "Bundle Definition"
.PP
.nf
\f(CW bundle
   tag          \fItag\fP    architecture \fIarchitecture\fP    Empty string
   location     \fIlocation\fP        <\fIbundle\&.directory\fP>
   qualifier    \fIqualifier\fP       Empty string
   revision     \fIrevision\fP        Empty string
   vendor_tag   \fIvendor_tag\fP      Empty string
   create_time  \fIcreate_time\fP     None
   description  \fIdescription\fP     Empty string
   contents     \fIcontents\fP        Empty string
   copyright    \fIcopyright\fP       Empty string
   directory    \fIdirectory\fP       Empty string
   instance_id  \fIinstance_id\fP     \fB1\fP 
   is_locatable \fIis_locatable\fP    \fBtrue\fP 
   layout_version \fIlayoyt_version\fP  \fB1\&.0\fP   
   machine_type \fImachine_type\fP    Empty string
   mod_time     \fImod_time\fP        Empty string
   number       \fInumber\fP          Empty string
   os_name      \fIos_name\fP         Empty string
   os_release   \fIos_release\fP      Empty string
   os_version   \fIos_version\fP      Empty string
   size         \fIsize\fP            Empty string
   title        \fItitle\fP           Empty string
   category_tag \fIcategory_tag\fP    Empty list or patch  # C701
   is_patch     \fIis_patch\fP        false                # C701\fR
.fi
.PP
.PP
The \fItag\fP and \fIcontents\fP attributes are required in INDEX and PSF files\&.
The \fIsize\fP attribute is not allowed in either file\&. The value of \fIsize\fP is generated dynamically\&.
An INDEX file will contain a \fIinstance_id\fP attribute\&.
Bundle definitions for distributions will not contain either the
\fIlocation\fP or
\fIqualifier\fP,
\fIinstalled_software\fP objects may contain these attributes\&.
 
.SS "Product Definition"
.PP
.nf
\f(CW product
   tag               \fItag\fP               None
   architecture      \fIarchitecture\fP      Empty string
   location          \fIlocation\fP          <\fIproduct\&.directory\fP>
   qualifier         \fIqualifier\fP         Empty string
   revision          \fIrevision\fP          Empty string
   vendor_tag        \fIvendor_tag\fP        Empty string
   all_filesets      \fIall_filesets\fP      Empty list
   control_directory \fIcontrol_directory\fP <\fIproduct\&.tag\fP>
   copyright         \fIcopyright\fP         Empty string
   create_time       \fIcreate_time\fP       None
   directory         \fIdirectory\fP         \fB/\fP 
   description       \fIdescription\fP       Empty string
   instance_id       \fIinstance_id\fP       \fB1\fP 
   is_locatable      \fIis_locatable\fP      \fBtrue\fP    
   postkernel        \fIpostkernel\fP        Implemen\&. defined
   layout_version    \fIlayout_version\fP    \fB1\&.0\fP 
   machine_type      \fImachine_type\fP      Empty string
   number            \fInumber\fP            Empty string
   os_name           \fIos_name\fP           Empty string
   os_release        \fIos_release\fP        Empty string
   os_version        \fIos_version\fP        Empty string
   mod_time          \fImod_time\fP          None
   size              \fIsize\fP              None
   title             \fItitle\fP             title
   category_tag      \fIcategory_tag\fP      Empty list # C701
   is_patch          \fIis_patch\fP          false      # C701
   copyrighters      \fIcopyrighters\fP      None       # impl\&.
   build_root        \fIbuild_root\fP        None       # impl\&.
   build_host        \fIbuild_host\fP        None       # impl\&.
   source_package    \fIsource_package\fP    None       # impl\&.
   source_rpm        \fIsource_rpm\fP        None       # impl\&.
   all_patches       \fIall_patches\fP       None       # impl\&.
   url               \fIurl\fP               None       # impl\&.
   rpm_provides      \fIrpm_provides\fP      None       # impl\&.
   change_log        \fIchange_log\fP        None       # impl\&.\fR
.fi
.PP
.PP
The \fItag\fP and \fIcontrol_directory\fP attributes are required\&.
The 
\fIsize\fP attribute is not allowed in either file\&. The value of
\fIsize\fP is generated dynamically\&.
An INDEX file will contain a \fIinstance_id\fP attribute\&.
A product object can contain 
\fIcontrol_files\fP,
\fIfiles\fP, and,
\fIsubproducts\fP in the form of software definitions\&.
.PP
The product\&.\fIvendor_tag\fP refers to the downstream distributor\&.  This value is
be the analogous to the RPMTAG_RELEASE or debian_release attributes\&.  The original upstream author\&'s package, for example,
would not use this attribute because that package would not have a release part in its name,
but could (or should) provide a vendor object in the PSF\&.
.PP
The \fIarchitecture\fP attribute contains an implementation
defined name describing the architecture\&.  This attribute may be a pattern\&. 
The swbis implementation uses the output of GNU \fBconfig\&.guess\fP (timestamp=2007-01-15) as the string to be matched by this pattern\&.
 
.SS "Category Definition"
.PP
.nf
\f(CW category
   tag           \fItag\fP            None             # C701
   title         \fItitle\fP          Empty string     # C701
   description   \fIdescription\fP    Empty string     # C701
   revision      \fIrevision\fP       Empty string     # C701\fR
.fi
.PP
.PP
The Category definition describes attributes of products and bundles related
to its category\&. If \fIis_patch\fP is "true" then category\&.tag
must equal "patch"\&.
 
.SS "Subroduct Definition"
.PP
.nf
\f(CW subproduct
   tag           \fItag\fP            None
   create_time   \fIcreate_time\fP    None
   description   \fIdescription\fP    Empty string
   mod_time      \fImod_time\fP       None
   size          \fIsize\fP           None
   title         \fItitle\fP          Empty string
   contents      \fIcontents\fP       Empty list
   category_tag  \fIcategory_tag\fP   Empty list   # C701
   is_patch      \fIis_patch\fP       false        # C701\fR
.fi
.PP
.PP
The \fItag\fP and \fIcontents\fP attributes are required\&.
 
.SS "Fileset Definition"
.PP
.nf
\f(CW fileset
   tag               \fItag\fP               None
   create_time       \fIcreate_time\fP       None
   mod_time          \fImod_time\fP          None
   control_directory \fIcontrol_directory\fP <\fIfileset\&.tag\fP>
   corequisites      \fIcorequisites\fP      Empty list
   description       \fIdescription\fP       Empty string
   exrequisites      \fIexrequisites\fP      Empty list
   is_kernel         \fIis_kernel\fP         \fBfalse\fP 
   is_locatable      \fIis_locatable\fP      \fBtrue\fP 
   is_reboot         \fIis_reboot\fP         \fBfalse\fP 
   location          \fIlocation\fP          <\fIproduct\&.directory\fP>
   media_sequence_number \fImedia_sequence_number\fP \fB1\fP 
   prerequisites     \fIprerequisites\fP     Empty list
   revision          \fIrevision\fP          None
   size              \fIsize\fP              None
   state             \fIstate\fP             None
   title             \fItitle\fP             Empty string
   is_sparse         \fIis_sparse\fP        "false"        # C701
   is_patch          \fIis_patch\fP         "false"        # C701
   category_tag      \fIcategory_tag\fP      empty list    # C701
   ancestor          \fIancestor\fP          <\fIproduct\&.tag\fP>,ver_id # C701
   applied_patches   \fIapplied_patches\fP   empty list    # C701
   patch_state       \fIpatch_state\fP       applied or,   # C701
                                           committed or,
                                             superseded, (no default)\&.
   saved_files_directory  \fIsaved_files_directory\fP None # C701
   supersedes       \fIsupersedes\fP          None         # C701
   superseded_by    \fIsuperseded_by\fP       None         # C701\fR
.fi
.PP
.PP
The \fItag\fP and \fIcontrol_directory\fP attributes are required\&.  A PSF should not contain the
\fIlocation\fP,
\fImedia_sequence_number\fP,
\fIsize\fP, or 
\fIstate\fP attributes\&.
A fileset object can contain 
\fIcontrol_files\fP,
\fIfiles\fP,
in the form of software definitions\&.
 
.SS "File Definition"
.PP
.nf
\f(CW file
   path               \fIpath\fP               None
   cksum             \fIcksum\fP             None
   compressed_cksum  \fIcompressed_cksum\fP  None
   compressed_size    \fIcompressed_size\fP    None
   compression_state  \fIcompression_state\fP  \fBuncompressed\fP 
   compression_type   \fIcompression_type\fP   Empty string
   revision           \fIrevision\fP           Empty string
   size               \fIsize\fP               None
   source             \fIsource\fP             None
   gid                \fIgid\fP                Undefined
   group              \fIgroup\fP              Empty string
   is_volatile        \fIis_volatile\fP        \fBfalse\fP 
   link_source        \fIlink_source\fP        None
   major              \fImajor\fP              None
   minor              \fIminor\fP              None
   mode               \fImode\fP               None
   mtime              \fImtime\fP              None
   owner              \fIowner\fP              Empty string
   type               \fItype\fP               \fBf\fP 
   uid                \fIuid\fP                undefined
   archive_path    \fIarchive_path\fP    empty string    # C701
   md5sum          \fImd5sum\fP      empty string    # impl\&.
   sha1sum         \fIsha1sum\fP      empty string    # impl\&.
   sha512sum       \fIsha512sum\fP      empty string    # impl\&.
   rdev            \fIrdev\fP            empty string    # impl\&.
   rpm_fileflags   \fIrpm_fileflags\fP   empty string    # impl\&.\fR
.fi
.PP
.PP
A PSF must contain \fIsource\fP attribute\&.
A \fIsource\fP  attribute in an INFO will be
ignored\&.
A PSF should not contain the
\fIcksum\fP,
\fIcompressed_cksum\fP,
\fIcompressed_size\fP,
\fIcompression_state\fP,
\fIcompression_type\fP, or  
\fIsize\fP attributes\&.
 
.SS "Control File Definition"
.br
.PP
.nf
\f(CW control_file
   tag                \fItag\fP                None
   cksum             \fIcksum\fP             None
   compressed_cksum  \fIcompressed_cksum\fP  None
   compressed_size    \fIcompressed_size\fP    None
   compression_state  \fIcompression_state\fP  \fBuncompressed\fP 
   compression_type   \fIcompression_type\fP   Empty string
   revision           \fIrevision\fP           Empty string
   size               \fIsize\fP               None
   source             \fIsource\fP             None
   path               \fIpath\fP               None
   interpreter        \fIinterpreter\fP        \fBsh\fP 
   result             \fIresult\fP             \fBnone\fP\fR
.fi
.PP
.PP
A control_file defines a control script such as those listed below (see Extended Control File Definitions)
or an attribute stored as a file\&. 
 
.SH "SOFTWARE SELECTIONS"
.PP
The Software Selections provide a means to specify and select (possibly with
a shell matching pattern) specific Software objects\&.  A selection is made
using a \fBsoftware spec\fP\&.
A software spec may not contain white space (a list of multiple selections is white space
delimited)\&.  A software spec consists of \fItag\fP values
and  \fIversion_id\fPs\&.  Multiple tags are \&'\&.\&' (dot) delimited
with the leftmost specifying the broadest (most general) software object such as a
bundle or product and the rightmost being most specific (The swbis implementation
does not support fileset tags in a software spec)\&. The tags may be followed by nothing, or a comma and one
or more Version Identifiers which are \&',\&' comma delimited\&. 
.PP
\fBDependency Specs\fP are software specs\&. 
.SS "Version Identifiers"
.PP
\fBVersion Identifiers\fP specify specific attributes of a software object\&.
There are five (5) specified\&. They are signified by a single letter: \fBr,a,v,l,q\fP\&.
An implementation may support additional ones and may support qualification
to a specific object type by prefixing a \&'p\&' or \&'b\&' or \&'f\&' for bundle, product, or
fileset respectively\&.  The value of the attribute follows an equals sign \&'=\&', or
in the case of a revision id, a relational operator\&.
.PP
.nf
\f(CW Letter     Attribute  
   r    \fBrevision\fP   r\<\fIrelop\fP\>\fIrevsion\fP   
                             # A relop may be ==,\<,\>,\<=,\>=
   v    \fBvendor_tag\fP    v=\fIvendor_tag\fP   
   q    \fBqualifier\fP     q=\fIqualifier\fP  
   l    \fBlocation\fP      l=\fIlocation\fP  
   a    \fBarchitecture\fP  a=\fIarch\fP  \fR
.fi
.PP
.PP
Implementation Extension Version Ids are the following:
.PP
.nf
\f(CW Letter     Attribute  
   i    \fIcatalog_instance_id\fP   i=\fInumber\fP  \fR
.fi
.PP
 The catalog \fIinstance_id\fP is a directory in the installed
software catalog that distinguishes installed instances of packages with the same
name and revision but at different locations\&.
.SS "Example Software Specs"
.PP
.nf
\f(CW    emacs,r==21\&.2
    kde\&.kdegames # This assumes that \&'kde\&' was specified as the bundle
                 # in the kdegames package
    foobar,r\>1\&.0,v=tycoon003
    somepackage,r\>1\&.0,r\<=1\&.3  # revision is the product revision by default
    somepackage,pr\>1\&.0,pr\<=1\&.3  # explicitly specify revision is the product revision\fR
.fi
.PP
 
.SH "DEPENDENCY SPECS"
.PP
A dependency spec is a \fBsoftware spec\fP\&.  There are three types:
\fIprerequisites\fP,
\fIexrequisites\fP,
\fIcorequisites\fP\&.
These attributes apply to the fileset and are placed in the fileset object in a PSF file\&.
A \fIprerequisites\fP is something that must be installed, and
a \fIexrequisites\fP is something that must not be installed\&.
A \fIcorequisites\fP is something that must be installed with, \fIcorequisites\fP are not supported at this time\&.
\fIprerequisites\fP map to RPMTAG_REQUIRENAME, RPMTAG_REQUIREVERSION, and RPMTAG_REQUIREFLAGS attributes\&.
.SS "Dependency Spec Examples"
.PP
.PP
.nf
\f(CW   # Alternation  Require a package named foo1 or foo2
   prerequisite   foo1|foo2

   # Require a package named foo1 and foo2
   prerequisite   foo1 foo2

   # multiple prerequisite keywords can be used
   prerequisite  foo1
   prerequisite  foo2

   # Require a revision range and a certain vendor_tag
   prerequisite  foo1,r>2,r<3,v=mydist*\fR
.fi
.PP
.SH "EXTENDED DEFINITIONS"
.PP
A Product Specification File (PSF) can contain Extended Definitions in the
\fBfileset\fP, \fBproduct\fP or \fBbundle\fP software definitions\&.  They would have the same level or containment
relationship as a
\fBfile\fP or
\fBcontrol_file\fP definition in the same contaning object\&.
.PP
Extended Definitions represent a minimal, expressive form for specifying files and file attributes\&.
Their use in a PSF is optional in that an equivalent PSF can be constructed without using them,
however, their use is encouraged for the sake of brevity and orthogonality\&.
.PP
The swbis implementation requires that no [ordinary] attributes appear after Extended Definitions
in the containing object, and, requires that Extended Definitions appear before logically contained objects\&.
That is, the parser uses the next object keyword to syntacticly and logically terminate the
current object even if the current object has logically contained objects\&.
.SS "o  Extended Control File Definitions"
.PP
.nf
\f(CW
.br
     checkinstall  \fIsource\fP  [\fIpath\fP]
     preinstall    \fIsource\fP  [\fIpath\fP]
     postinstall   \fIsource\fP  [\fIpath\fP]
     verify        \fIsource\fP  [\fIpath\fP]
     fix           \fIsource\fP  [\fIpath\fP]
     checkremove   \fIsource\fP  [\fIpath\fP]
     preremove     \fIsource\fP  [\fIpath\fP]
     postremove    \fIsource\fP  [\fIpath\fP]
     configure     \fIsource\fP  [\fIpath\fP]
     unconfigure   \fIsource\fP  [\fIpath\fP]
     request       \fIsource\fP  [\fIpath\fP]
     unpreinstall  \fIsource\fP  [\fIpath\fP]
     unpostinstall \fIsource\fP  [\fIpath\fP]
     space         \fIsource\fP  [\fIpath\fP]
     control_file  \fIsource\fP  [\fIpath\fP]\fR
.fi
.PP
.PP
The \fIsource\fP attribute defines the location in distributors\&'s development system
where the swpackage utility will find the script\&.  The keyword is the value of the 
\fItag\fP attribute
and tells the utilities when to execute the script\&.
The \fIpath\fP attribute is optional and specifies the file name in the packages distribution
relative to the control_directory for software containing the script\&. If not given the 
\fItag\fP value is used as the filename\&.
.SS "o  Directory Mapping"
.PP
.nf
\f(CW
.br
   directory  \fIsource\fP  [\fIdestination\fP]
.br
\fR
.fi
.PP
.PP
Applies the \fIsource\fP attribute as the directory under which
the subsequently listed files are located\&.  If 
\fIdestination\fP is defined it will be used as a prefix to the 
\fIpath\fP (implied) file definition\&.  
\fIsource\fP is typically a temporary or build
location and 
\fIdest\fP is its unrealized absolute pathname destination\&.
.SS "o  Recursive File Definition"
.PP
.nf
\f(CW
.br
  file *
.br
\fR
.fi
.PP
.PP
Specifies every file in current source directory\&.
The \fIdirectory\fP extended definition must be used before the recursive specification\&.
.SS "o  Explicit File Definition"
.PP
.nf
\f(CW
.br
  file [-t \fItype\fP] [-m \fImode\fP] [-o \fIowner\fP[,\fIuid\fP]] [-g \fIgroup\fP[,\fIgid\fP]] [-n] [-v] source [\fIpath\fP]
.br
\fR
.fi
.PP
.PP
\fBsource\fP 
.RS
 
.PP
\fIsource\fP defines the pathname of the file to be used as the source of file data
and/or attributes\&.
If it is a relative path, then swpackage searches for this file relative to the
the source argument of the \fBdirectory\fP keyword, if set\&.
If \fBdirectory\fP keyword is not set then the search is relative to the
current working directory of the swpackage utility\&'s invocation\&.
.PP
All attributes for the destination file are taken from the source file, unless a
\fBfile_permissions\fP keyword is active, or the -m, -o, or -g options are also
included in the file specification\&.
.RE
.PP
\fBpath\fP 
.RS
 
\fIpath\fP defines the destination path where the file will be created or installed\&.
If it is a relative path, then the destination path of the of the
\fBdirectory\fP keyword must be active and will be used as the path prefix\&.
If path is not specified then 
\fIsource\fP is used as the value of path and directory mapping applied (if active)\&.
.RE
.PP
\fB-t type\fP 
.RS
 
\fItype\fP may one of \&'d\&' (directory), or  \&'h\&' (hard link), or \&'s\&' (symbolic link)\&.
.PP
-t d  Create a directory\&.
.br
If \fIpath\fP is not specified
\fIsource\fP is used as the path attribute\&.
.PP
-t h  Create a hard link\&.
.br
\fIpath\fP and \fIsource\fP are specified\&.
\fIsource\fP is used as the value of the 
\fIlink_source\fP attribute, and
\fIpath\fP is the value of the path attribute\&.
.PP
-t s  Create a symbolic link\&.
.br
\fIpath\fP and \fIsource\fP are specified\&.
\fIsource\fP is used as the value of the 
\fIlink_source\fP attribute, and
\fIpath\fP is the value of the path attribute\&.
.RE
.PP
\fB-m mode\fP 
.RS
 
\fImode\fP defines the octal mode for the file\&.
.RE
.SS "o  Default Permission Definition"
.PP
.nf
\f(CW
.br
  file_permissions [-m \fImode\fP] [-u \fIumask\fP] [-o [\fIowner\fP[,]][\fIuid\fP]] [-g [\fIgroup\fP[,]][\fIgid\fP]]
.br
\fR
.fi
.PP
.PP
Applies to subsequently listed file definitions in a fileset\&.  
These attributes will apply where the file attributes were not specified explicitly in a 
file definition\&.
Subsequent \fBfile_permissions\fP definitions
simply replace previous definitions (resetting all the options)\&.
.PP
To reset the file_permission state (i\&.e\&. turn it off) use one of the following:
    file_permissions "" 
.br
	or the preferred way is
.br
    file_permissions -u 000
.SS "o  Excluding Files"
.PP
.nf
\f(CW
.br
   exclude source
.br
\fR
.fi
.PP
.PP
Excludes a previously included file or an entire directory\&.
.br
.SS "o  Including Files"
.PP
.nf
\f(CW
.br
   include <\fIfilename\fP
.br
\fR
.fi
.PP
.PP
The contents of \fIfilename\fP may be more definitions for files\&.
The syntax of the included file is PSF syntax\&.
.br
.SH "DISTRIBUTOR KEYWORDS"
.PP
A software definition file (INFO, INDEX or psf) may contain keywords not recognized by the standard\&. 
Such keywords will be parsed as an attribute keyword, that is as an attribute of the
containing object (keyword) software definition\&.
.SH "PACKAGE SECURITY"
.PP
The Package Security Attributes are distribution attributes stored as separate files\&.  They are implementation extensions\&.
They consist of archive digests, catalog signature, catalog signature header, and individual file md5, sha1, and sha512 digests\&.
.PP
.SS "Archive Digests"
.PP
\fImd5sum\fP, \fIsha1sum\fP, and \fIsha512sum\fP are the md5 and sha1 and sha512 digests (ascii representations) of the
leading package directories that do not have the \fBcatalog\fP pathname component
followed by the 
\fIsoftware file storage structure\fP portion of the uncompressed serial access package file including all archive format trailer blocks\&.
.PP
.nf
\f(CW       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBmd5sum\fP
.br
       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBsha1sum\fP
.br
       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBsha512sum\fP
.br
\fR
.fi
.PP
.SS "Adjunct Md5 Digest"
.PP
\fIadjunct_md5sum\fP is the same as the
\fImd5sum\fP excluding symbolic links\&.
If a package does not contain symbolic links the 
\fImd5sum\fP and 
\fIadjunct_md5sum\fP will be identical\&.
.br
.PP
.nf
\f(CW       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBadjunct_md5sum\fP\fR
.fi
.PP
.PP
Explanation: This attribute is called \&'adjunct\&' because it is a digest of a subset of the files in the package\&.
It exists to facilitate verifying file integrity of the directory form of a package
in an environment where the modification time of symbolic link files are not preserved from the serial
archive by the tar utility or operating system\&.
The ability to verify even the \fIadjunct_md5sum\fP from
the directory form of the package is dependent on the tar creating utility and 
other attributes of a POSIX\&.2 environment\&.
.SS "Catalog Signature Header"
.PP
The \fIsig_header\fP file is a ustar header that is
identical bit-for-bit to the ustar header of the signature file\&.  It always precedes the signature
file archive members\&.
.PP
.nf
\f(CW       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBsig_header\fP\fR
.fi
.PP
.PP
The \fIsig_header\fP protects the tar header of the signature files from tampering\&.
This is required because neither the signature file bytes nor the signature tar header are
included in the signed data\&.
.SS "Catalog Signature"
.PP
The signature protects the metadata section of the archive\&.  The contents of payload section are only included
in the form of a crytographic digest\&.  The sha1 digest is preferred over the md5 digest for technical reasons\&.
If the metadata section does not contain the payload section digests then there is no way to verify the
payload from the signature\&.
.PP
.PP
.nf
\f(CW       <\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBsignature\fP\fR
.fi
.PP
.PP
The signed data is the \fIexported catalog structure\fP of the uncompressed serial archive package file
up to but not including the first byte of the \fIsoftware file storage structure\fP followed by two (2) 512 byte null blocks if tar format, and no trailer bytes if not tar format\&. 
The signature file archive member itself is not included in the signed stream, it is intended that the 
<\fIpath\fP>/\fBcatalog\fP/<\fIdfiles\fP>/\fBmd5sum\fP file is included in the signed stream\&.
.PP
The signature file is ASCII armored\&.
The last printable character of the signature is followed by one or more
newline characters (0x0A)\&.
The total length of the file must match the file size specified
in the size field of the \fBsig_header\fP file\&.
The ustar header of every signature archive member shall be identical
to the \fBsig_header\fP file\&.
The padded size is predetermined [by swpackage] and currently set
to be 1024 octets\&.
This means the armored sig file has a length limitation of 1023 octets\&.
.PP
If multiple signature archive members exist they must follow one another in the
archive with no other intervening files; and, the same
\fBsig_header\fP file is the ustar header for all the signature
archive members\&.
A signature archive member, whether alone or one of many, is never
part of the signed data stream\&.
.SS "File Digests"
.PP
File digests are attributes of the \fBfile\fP software definition\&. They appear in
the INFO file\&. 
       \fIfile\fP\&.cksum 
       \fIfile\fP\&.md5sum 
       \fIfile\fP\&.sha1sum 
       \fIfile\fP\&.sha512sum
.PP
Each file can have none or all of these digests\&.
.br
.br
.SH "SOFTWARE DEFINITION FILES"
.PP
The metadata files, INDEX, INFO and PSF, contain information about the
software in the form of \fIsoftware definitions\fP\&. 
The INDEX and INFO files appear
in a package directory structure\&.
They are automatically generated by the \&'swpackage\&' command\&.
The location in the directory structure indicates the higher level object
to which their data pertains\&.
The PSF file does not appear in the package\&.
It is created by a person or program and it directs
the action of the swpackage utility\&.
It is internal data unless released by the distributor\&.
.PP
The files contain keywords (and values) to represent the attributes defined in the standard\&.  There are three (3)
different keyword types: object, attribute, and, extended\&. The object keyword type has no value and there are
eleven (11) of these corresponding to the Software Definitions defined above:
\fBinstalled_software\fP,
\fBdistribution\fP,
\fBmedia\fP,
\fBbundle\fP,
\fBvendor\fP,
\fBcategory\fP,
\fBproduct\fP,
\fBsubproduct\fP,
\fBfileset\fP,
\fBcontrol_file\fP,
\fBfile\fP\&.

Each object keyword is followed by and newline and attributes in the form of keyword/value pairs\&.  Whitespace separates the keyword and
value\&.  Whitespace outside of a quoted value is not significant\&. 
A quoted value can span multiple lines\&.  An object keyword with its list of attribute keywords (and values)
forms a \fISoftware Definition\fP\&.  
A \fISoftware Definition\fP is terminated by the start of the next \fISoftware Definition\fP\&.
Extended keywords (meaning Extended Definitions) only appear in a PSF file\&.
.PP
The order  of objects (i\&.e \fISoftware Definition\fPs) is significant and
a containment  hierarchy is determined according to parser\&'s grammar\&.
.SS "Additional Syntax Rules"
.IP "   \(bu" 6
A \&'#\&' (pound) character designates a comment\&.  A comment may begin a line or appear at the
end of a single line containing the keyword/value pair\&.
.IP "   \(bu" 6
A value may be quoted by the \&'"\&' (double quote) character; and, multi-line values must be quoted\&.
Trailing white space from an unquoted value will be removed\&.
.IP "   \(bu" 6
The order of attributes is not significant although the INDEX file grammar requires the \fIlayout_version\fP attribute
appear first in
distribution or installed software object\&.
.IP "   \(bu" 6
The ", #, and, \\ characters must be escaped with a backslash (\\) in a quoted value\&.
.IP "   \(bu" 6
If a value begins with a < (less than), the value is interpreted as a filename
whose contents will be treated as a quoted value although the storage of the attribute
will be in the form of a control file (i\&.e\&. a separate file in the control directory)\&.
For INDEX files, the filename is relative to the control directory in which this attribute is contained\&.
For PSF files, the filename is a path on the host\&.
.SS "Software Definition File Grammar"
.PP
A PSF may contain all \fISoftware Definitions\fP\&.  An INDEX file does not contain
\fBcontrol_file\fP, 
or
\fBfile\fP definitions\&. An INFO file contains only
\fBcontrol_file\fP,
and
\fBfile\fP definitions\&.
.PP
.nf
\f(CW
.br
     software_definition_file : INDEX 
                              | INFO 
                              | PSF
                              ;
     
     PSF :  distribution_definition
            swo_contents
            ;
     
     INDEX : swo_definition
             swo_contents
            ;
    
     INFO : fileset_contents
            ;

     swo_definition : distribution_definition
                    | \fIinstalled_software\fP 
                    ;
    
     distribution_definition : \fIdistribution\fP 
                                         \fImedia\fP 
                             ;

     swo_contents : \fIvendor\fP(s)
                   | \fIcategory\fP(s)
                   | products
                   | bundles
                   ;
     
     products : \fIproduct\fP 
                product_contents
                ;
     
     bundles : \fIbundle\fP 
                ;
     
     product_contents :  \fIcontrol_file\fPs
       /* control_files not valid in INDEX file */ 
                     | \fIsubproduct\fPs
                     |  filesets
		     ;
    
     filesets : \fIfileset\fP 
      /* fileset_contents not valid in INDEX file */
                fileset_contents
                ;

     fileset_contents :  \fIcontrol_file\fPs
                      | \fIfile\fPs
                      ;
\fR
.fi
.PP
.SH "EXAMPLE PACKAGE"
.SS "Layout"
.PP
.PP
.nf
\f(CW swm-1\&.0/catalog
 swm-1\&.0/catalog/INDEX
 swm-1\&.0/catalog/dfiles
 swm-1\&.0/catalog/dfiles/INFO
 swm-1\&.0/catalog/dfiles/md5sum
 swm-1\&.0/catalog/dfiles/sha1sum
 swm-1\&.0/catalog/dfiles/adjunct_md5sum
 swm-1\&.0/catalog/dfiles/sig_header
 swm-1\&.0/catalog/dfiles/signature
 swm-1\&.0/catalog/gsoft_swm
 swm-1\&.0/catalog/gsoft_swm/pfiles
 swm-1\&.0/catalog/gsoft_swm/pfiles/INFO
 swm-1\&.0/catalog/gsoft_swm/pfiles/remove
 swm-1\&.0/catalog/gsoft_swm/pfiles/configure
 swm-1\&.0/catalog/gsoft_swm/bin
 swm-1\&.0/catalog/gsoft_swm/bin/INFO
 swm-1\&.0/catalog/gsoft_swm/bin/postinstall
 swm-1\&.0/catalog/gsoft_swm/bin/configure
 swm-1\&.0/catalog/gsoft_swm/doc
 swm-1\&.0/catalog/gsoft_swm/doc/INFO
 swm-1\&.0/catalog/gsoft_swm/doc/postinstall
 swm-1\&.0/gsoft_swm
 swm-1\&.0/gsoft_swm/bin
 swm-1\&.0/gsoft_swm/bin/usr/bin/swpackage
 swm-1\&.0/gsoft_swm/bin/usr/bin/sw_build
 swm-1\&.0/gsoft_swm/doc
 swm-1\&.0/gsoft_swm/doc/usr/man/man1/swpackage\&.1
 swm-1\&.0/gsoft_swm/doc/usr/man/man1/sw_build\&.1\fR
.fi
.PP
.SS "Hypothetical PSF file"
.PP
.nf
\f(CW
.br
 
 distribution
   control_directory swm-1\&.0  #Implementation Extension\&.
   vendor
     the_term_vendor_is_misleading  false # True or False 
     tag greatsoft 
     title Greatersoft Corporation
     description "Greatersoft Corporation, Inc\&."
   product
     tag swm
     title POSIX 1387 package builder
     revision 1\&.0
     control_directory gsoft_swm
     vendor_tag greatsoft
     description A package building Utility\&.
     machine_type i386
     control_file
     	path remove 
        source /var/tmp/sw/remove\&.source
     configure /var/tmp/sw/configure\&.source
     fileset
        tag bin
        control_directory bin
        title Executable Files
        state available
     	postinstall /var/tmp/sw/bin/postinstall
        configure /var/tmp/sw/bin/configure
        file -m 0755 -o root -g root /var/tmp/sw/build/bin/swpackage  \\
                     /usr/bin/swpackage
        file -m 0755 -o root -g root /var/tmp/sw/build/bin/sw_build  \\
                     /usr/bin/sw_build
   fileset
      tag doc
      control_directory doc
      title Manual Pages
      state available
      postinstall /var/tmp/sw/bin/postinstall
      file -m 0644 -o root -g root /var/tmp/sw/build/man/swpackage\&.1 \\
                /usr/man/man1/swpackage\&.1
      file 
         mode 0644 
         owner root 
         group  root
         source /var/tmp/sw/build/man/sw_build\&.1  
         path /usr/man/man1/sw_build\&.1\fR
.fi
.PP
.SS "INDEX File swm-1\&.0/catalog/INDEX"
.PP
.nf
\f(CW
.br
 
 distribution
   layout_version 1\&.0
   tag swm-1\&.0
   uuid 880ccf8b-de2c-4422-bff0-fd686279da73
   md5sum < md5sum
   adjunct_md5sum < adjunct_md5sum
   sig_header < sig_header
   signature < signature
   media
     sequence_number 1
   vendor
     the_term_vendor_is_misleading  false # True or False 
     tag greatsoft 
     title Greatersoft Corporation
     description "Greatersoft Corporation, Inc\&."
   product
     tag swm
     title POSIX 1387 package builder
     revision 1\&.0
     instance_id 1
     control_directory gsoft_swm
     vendor_tag greatsoft
     description A package building Utility\&.
     machine_type i386
     fileset
        tag bin
        control_directory bin
        size 196643
        title Executable Files
        state available
     fileset
        tag doc
        control_directory doc
        size 19643
        title Manual Pages
        state available\fR
.fi
.PP
.SS "INFO File swm-1\&.0/catalog/dfiles/INFO"
.PP
.nf
\f(CW 
 control_file
   path INFO
   tag INFO
   size 92
 control_file
   path md5sum
   tag md5sum
   size 36
 control_file
   path adjunct_md5sum
   tag adjunct_md5sum
   size 36
 control_file
   path sig_header
   tag sig_header
   size 512
 control_file
   path signature
   tag signature
   size 512 \fR
.fi
.PP
.SS "INFO File swm-1\&.0/catalog/gsoft_swm/bin/INFO"
.PP
.nf
\f(CW 
 control_file
   path INFO
   tag INFO
   size 337
 
 control_file
   path postinstall
   type f
   size 803
   cksum 3928827394
   mode 550
   uid 0
   gid 0
   owner root
   group root
   mtime 739080341

 control_file
   path configure
   type f
   size 432
   cksum 3934546394
   mode 550
   uid 0
   gid 0
   owner root
   group root
   mtime 739340771

 file
   path /usr/bin/swpackage
   type f
   size 80860
   cksum 3929827394
   mode 755
   uid 0
   gid 0
   owner root
   group root
   mtime 739080771

 file
   path /usr/bin/sw_build
   type f
   size 120860
   cksum 9894925524
   mode 755
   uid 0
   gid 0
   owner root
   group root
   mtime 7393808731 \fR
.fi
.PP
 
.SH "SWBIS PSF CONVENTIONS"
.PP
This section describes attribute usage and conventions imposed by the swbis implementation\&.
Not all attributes are listed here\&.  Those that are have important effects or
particular interest\&.
.SS "o Distribution Attributes"
.PP
The standard defines a limited set of attributes for the distribution object\&.
An expanded set is suggested by the informative annex however a conforming
implementation is not required act on them\&.  The reason for this is a
distribution may be acted upon by a conforming utility in such a way that attributes
of the \fBdistribution\fP become invalid\&.
For this reason, some attributes that refer to an entire "package" [in other package managers]
are referred from the product object and attain their broadened scope by the distributor\&'s
convention that their distribution contains just one
\fBproduct\fP\&.
.PP
For example, the package NAME and VERSION are referred from the product tag and revision,
not the distribution\&'s\&.  This convention supports multiple products in a distribution and
is consistent with the standard\&. 
.PP
\fBtag\fP 
.RS
 
\fItag\fP is the short, file system friendly, name of the distribution\&.
Providing a distribution tag is optional\&.  The swbis implementation will use this as the
[single] path name prefix if there is no distribution\&.control_directory attribute\&.
A distribution tag attribute and swpackage\&'s response to it is an implementation extension\&.
The leading package path can also be controlled with the \&'\&'-W dir\&'\&' option\&. 
.RE
 
.PP
\fBcontrol_directory\fP 
.RS
 
\fIcontrol_directory\fP, in a distribution object, is the constant leading package path\&.
Providing this attribute is optional\&.
A distribution control_directory attribute and swpackage\&'s response to it is an implementation extension\&.
The leading package path can also be controlled with the \&'\&'-W dir\&'\&' option\&.  This attribute will be
generated by swpackage if not set in a PSF\&.
.RE
 
.SS "o Bundle Attributes"
.PP
A \fBbundle\fP defines a collection of products whether or not
the distribution has all the products present\&. 
.PP
\fBtag\fP 
.RS
 
\fItag\fP is the short, file system friendly, name of the bundle\&.
This value is used by the swbis implementation as a path name component in the
installed software catalog\&.  If it is not present the product tag is used\&.
.RE
 
.SS "o Product Attributes"
.PP
A \fBproduct\fP defines the software product\&.
.br
.PP
\fBtag\fP 
.RS
 
\fItag\fP is the short, file system friendly, name of the product\&.
This value is used by the swbis implementation as a path name component in the
installed software catalog\&.  It is required\&.  The swbis implementation uses it in a way 
that is analogous to the RPMTAG_NAME attribute, namely as the public recognizable name of
the package\&.
.RE
 
.PP
\fBcontrol_directory\fP 
.RS
 
Is the directory name in the distribution under which the product contents are located\&.
This value has no affect on the installed software catalog\&.  If it is not given in a PSF
then the
\fItag\fP is used\&.
.RE
 
.PP
\fBrevision\fP 
.RS
 
Is the product revision\&.  It should not contain a "RELEASE" attribute part or other
version suffix modifiers\&.
This value is used by the swbis implementation as a path name component in the
installed software catalog\&.  It is required by swinstall\&.
.RE
 
.PP
\fBvendor_tag\fP 
.RS
 
This is a short identifying name of the distributor that supplied the product and
may associate (refer to) a \fBvendor\fP object from the INDEX file that
has a matching tag attribute\&.
This attribute is optional\&.
This attribute value should strive to be unique among all distributors\&. The swbis implementation
modifies the intended usage slightly as a string that strives to be globally unique for a given
product\&.\fBtag\fP and product\&.\fBrevision\fP\&.
In this capacity it serves to distinguish products with the same revision and tag from the same or
different distributor\&.  It most closely maps to the RPMTAG_RELEASE or "debian_revision" attributes\&.
It is one of the version distinguishing attributes of a product specified by the standard\&. 
It is transfered into the installed_software catalog (not as a path name component) by swinstall\&.
If this attribute exists there should also be a
\fBvendor\fP object in the PSF in the distribution object that has this tag\&.
This attribute is assigned the value of RPMTAG_RELEASE by
swpackage when translating an RPM\&.
.RE
 
.PP
\fBarchitecture\fP 
.RS
 
This string is one of the version attributes\&.  It is used to disambiguate
products that have the same \fBtag\fP, \fBrevision\fP and \fBvendor_tag\fP\&.  It is not used for determining a products
compatibility with a host\&.
The form is implementation defined\&.
swbis uses the output of GNU \fBconfig\&.guess\fP as the value of
this string\&.  A wildcard pattern should not be used\&.
The canonical swbis architecture string can be
listed with \fBswlist\fP\&. For example
.PP
.nf
\f(CWswlist -a architecture @ localhost\fR
.fi
.PP
 Here are some example outputs from real systems\&.
.PP
.nf
\f(CW    System      `uname -srm`              architecture  
Red Hat 8\&.0:  Linux 2\&.4\&.18 i686        i686-pc-linux-gnu
OpenSolaris:  SunOS 5\&.11 i86pc         i386-pc-solaris2\&.11
NetBSD 3\&.1:   NetBSD 3\&.1 i386          i386-unknown-netbsdelf3\&.1
Red Hat 4\&.1:  Linux 2\&.0\&.36 i586        i586-pc-linux-gnulibc1
Debian 3\&.1:   Linux 2\&.6\&.8-2-386 i686   i686-pc-linux-gnu\fR
.fi
.PP
.RE
 
.PP
\fBos_name\fP 
\fBos_release\fP 
\fBos_version\fP 
\fBmachine_type\fP 
.RS
 
These attributes are used to determine compatibility with a host\&.
They correspond to the \fBuname\fP attributes defined by POSIX\&.1\&.
If an value is nil or non-existent it is assumed to match the host\&.
All attributes must match for there to be compatibility\&.  Distributors may
wish to make these values a shell pattern in their PSF\&'s so to match
the intended collection of hosts\&.
swbis uses \fBfnmatch\fP (with FLAGS=0) to determine a match\&.
.RE
 
.SS "o Fileset Attributes"
.PP
A \fBfileset\fP defines the fileset\&.
.br
.PP
\fBtag\fP 
.RS
 
\fItag\fP is the short, file system friendly, name of the fileset\&.
It is required although selection of filesets is  not yet supported therefore the end user
will have little to do with the fileset tag\&.
.RE
.PP
\fBcontrol_directory\fP 
.RS
 
Is the directory name in the product under which the fileset contents are located\&.
This value has no affect on the installed software catalog\&.  If it is not given in a PSF
then the
\fItag\fP is used\&.
.RE
.SS "o Example Source Package PSF"
.PP
This PSF packages every file is current directory\&. It uses nil control directories
so the package structure does not change relative to a vanilla tarball\&.
.PP
.nf
\f(CW
.br
 distribution
   description "fooit - a program from fooware
that does everything\&."
   title "fooit - a really cool program"
   COPYING < /usr/local/fooware/legalstuff/COPYING
 vendor
   the_term_vendor_is_misleading false
   tag fooware
   title fooware Consultancy Services, Inc\&.
   description ""
 vendor
   the_term_vendor_is_misleading true
   tag myfixes1
   title Bug fixes, Set 1
   description "a place for more detailed description"
 product
   tag fooit
   control_directory "" 
   revision 1\&.0
   vendor_tag myfixes1  # Matches the vendor object above
 fileset
    tag fooit-SOURCE
    control_directory ""
    directory \&.
    file *
    exclude catalog\fR
.fi
.PP
 
.SS "o Example Runtime (Binary) Package PSF"
.PP
This is a sample PSF for a runtime package\&.  It implies multiple products (e\&.g\&. sub-packages)
using the bundle\&.contents attribute\&.  Since the bundle and product tags exist in a un-regulated
namespace and are seen by end users they should be carefully chosen\&.   Note that the bundle
and product have the same tag which may force downstream users to disambiguate using software
selection syntax such as fooit,bv=* or fooit,pv=* \&.
.PP
.nf
\f(CW
.br
 distribution
   description "fooit - a program from fooware
that does everything\&."
   title "fooit - a really cool program"
   COPYING < /usr/local/fooware/legalstuff/COPYING

     vendor
        the_term_vendor_is_misleading false
        tag fooware
        title fooware Consultancy Services, Inc\&.
        description "Provider of the programs
 that do everything"

     vendor
        the_term_vendor_is_misleading true
         tag fw0
         title fooware fixes 
         description "More fixes from the fooware users"

#  Bundle definition:  Use a bundle
     bundle
         tag fooit
         vendor_tag fooware
         contents fooit,v=fw0 fooit-devel fooit-doc  

#  Product definition:
     product
         tag fooit   # This is the package name
         revision 1\&.0 # This is the package version
         vendor_tag fw0 # This is a release name e\&.g\&. RPMTAG_RELEASE
         postinstall scripts/postinstall
     fileset
          tag fooit-RUN
          file doc/man/man1/fooit\&.1 /usr/man/man1/fooit\&.1 
          file src/fooit /usr/bin/fooit\fR
.fi
.PP
 
.SH "APPLICABLE STANDARDS"
.PP
IEEE Std 1387\&.2-1995 (Identical to ISO 15068-2:1999),
Open Group CAE C701
.SH "SEE ALSO"
 XDSA C701 http://www\&.opengroup\&.org/publications/catalog/c701\&.htm
.br
 swbisparse(1) -- An implementation extension parser utility\&.
.br
 swcopy(8)
 swinstall(8)
 swbis(7)
 swbis(1)
 swpackage(5)
 swpackage(8)
 swverify(8)
.SH "IDENTIFICATION"
 Copyright (C) 2005 Jim Lowe
 Version: 1\&.13\&.1
 Last Updated: 2006-01
 Copying Terms: GNU Free Documentation License
.SH "BUGS"
.PP
None
.\" created by instant / docbook-to-man, Fri 02 Nov 2018, 20:39
